### Listar todas as tarefas
GET http://localhost:5022/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5022/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

###Listar todas as tarefas nao concluidas
GET http://localhost:5022/api/tarefas/naoconcluidas

###Listar todas as concluidas
GET http://localhost:5022/api/tarefas/concluidas

###Alterar
PUT  http://localhost:5022/api/tarefas/alterar/2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e

